[env:esp32_gatt_client]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200
upload_speed = 921600
upload_port = COM13
monitor_port = COM13

lib_deps =
    h2zero/NimBLE-Arduino @ ^1.4.1
